In [1]:
from numpy import random

x = random.randint(200)
print(x)

183


In [2]:
from numpy import random  

x = random.rand()
print(x)

0.6215453842111974


In [3]:
from numpy import random

x = random.randint(100, size=(5))
print(x)

[97 88 38 34  2]


In [4]:
from numpy import random

x = random.randint(200, size=(3, 5))
print(x)

[[ 27  21 192 119 183]
 [164 112 146  62  56]
 [180  13 126   9 105]]


In [5]:
from numpy import random

x = random.rand(5)
print(x)

[0.9625125  0.25326832 0.04569273 0.81795964 0.31364513]


In [6]:
from numpy import random

x = random.rand(3, 5)
print(x)

[[0.81223278 0.44240227 0.9483191  0.69232807 0.71890334]
 [0.59614564 0.87373503 0.51234607 0.62231942 0.529793  ]
 [0.6489524  0.27032661 0.53939184 0.61032825 0.70980877]]


In [7]:
from numpy import random

x = random.choice([3, 5, 7, 9])
print(x)

5


In [8]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[3 3 7 7 9]
 [7 7 9 3 3]
 [9 3 5 7 5]]


In [9]:
from numpy import random

# Define values and their probabilities
values = [3, 5, 7, 9]
probabilities = [0.1, 0.3, 0.6, 0.0]

# Generate a 1-D array with 100 values based on probabilities
x = random.choice(values, p=probabilities, size=(100))

print(x)

[5 7 5 5 7 5 7 7 5 7 5 5 7 5 5 7 7 7 7 7 5 7 3 7 7 7 5 7 5 3 5 5 7 3 5 7 5
 7 7 7 5 5 7 7 7 7 5 7 7 7 7 7 3 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 5 5 7 5
 7 5 5 7 7 7 7 7 7 7 7 7 7 3 5 3 5 7 5 3 7 7 3 7 7 7]


In [10]:
from numpy import random

# Define values and their probabilities
values = [3, 5, 7, 9]
probabilities = [0.1, 0.3, 0.6, 0.0]

# Generate a 2-D array with 3 rows and 5 columns based on probabilities
x = random.choice(values, p=probabilities, size=(3, 5))

print(x)

[[7 7 5 7 7]
 [7 5 7 5 7]
 [7 7 5 7 7]]


In [11]:
from numpy import random
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Shuffle the array in-place
random.shuffle(arr)

# Print the shuffled array
print(arr)

[5 1 2 4 3]


In [12]:
from numpy import random
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Generate a random permutation of the array
permuted_arr = random.permutation(arr)

# Print the random permutation
print(permuted_arr)

[2 1 4 3 5]
