In [1]:
from numpy import random

x = random.randint(200)
print(x)

161


In [2]:
from numpy import random  

x = random.rand()
print(x)

0.46102272483924056


In [3]:
from numpy import random

x = random.randint(100, size=(5))
print(x)

[59 98 25 34 95]


In [4]:
from numpy import random

x = random.randint(200, size=(3, 5))
print(x)

[[ 95 196  37  93  40]
 [ 79  90  73 137 171]
 [ 15 166 159 110  88]]


In [5]:
from numpy import random

x = random.rand(5)
print(x)

[0.26061739 0.53480824 0.32829086 0.74623641 0.95757071]


In [6]:
from numpy import random

x = random.rand(3, 5)
print(x)

[[0.24367801 0.55259421 0.70885151 0.65429482 0.76240307]
 [0.4123537  0.91362093 0.11036977 0.6470394  0.35274607]
 [0.85004054 0.91940489 0.73615978 0.94343244 0.44482358]]


In [7]:
from numpy import random

x = random.choice([3, 5, 7, 9])
print(x)

9


In [8]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[5 3 7 3 5]
 [3 5 9 7 3]
 [5 3 3 9 3]]


In [9]:
from numpy import random

# Define values and their probabilities
values = [3, 5, 7, 9]
probabilities = [0.1, 0.3, 0.6, 0.0]

# Generate a 1-D array with 100 values based on probabilities
x = random.choice(values, p=probabilities, size=(100))

print(x)

[7 7 7 5 7 7 7 7 7 5 7 3 5 5 3 7 5 7 7 5 5 7 3 7 5 7 7 5 3 7 3 7 7 7 7 7 7
 5 7 5 7 7 7 5 7 7 7 7 7 5 7 5 5 7 5 7 5 5 7 7 5 5 7 5 7 5 7 7 7 3 5 5 7 7
 7 7 7 5 3 7 7 5 7 3 3 7 3 7 7 5 7 7 7 7 5 5 7 5 3 7]


In [10]:
from numpy import random

# Define values and their probabilities
values = [3, 5, 7, 9]
probabilities = [0.1, 0.3, 0.6, 0.0]

# Generate a 2-D array with 3 rows and 5 columns based on probabilities
x = random.choice(values, p=probabilities, size=(3, 5))

print(x)

[[7 5 3 7 5]
 [7 7 3 3 7]
 [5 7 7 5 3]]


In [11]:
from numpy import random
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Shuffle the array in-place
random.shuffle(arr)

# Print the shuffled array
print(arr)

[1 5 4 3 2]


In [12]:
from numpy import random
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Generate a random permutation of the array
permuted_arr = random.permutation(arr)

# Print the random permutation
print(permuted_arr)

[1 2 5 4 3]
